stages:
  - master
  - github

test:
  stage: master
  cache:
    paths:
      - vendor/
  before_script:
    # Install composer dependencies
    - composer install
  script:
    - ./vendor/bin/codecept run unit
  tags:
    - php

github_deploy:
    stage: github
    before_script:
        - echo "$DEPLOY_KEY_GITHUB" > ./deploy_key
        - chmod 0600 ./deploy_key
    script:
        - ssh -v -i ./deploy_key "$DEPLOY_REMOTE_REP" -o StrictHostKeyChecking=no
        - git remote add github git@github.com:mallgroup/mpapi-client-php.git
        - git fetch github
        - git push github
    after_script:
        - rm -f ./deploy_key
    only:
        - master