stages:
  - master
  - deploy

test:
  stage: master
  cache:
    paths:
      - vendor/
  before_script:
    # Install composer dependencies
    - composer install
  script:
    - ./vendor/bin/codecept run unit
  tags:
    - php
  
deploy:
  stage: deploy
  script:
    - git push "${DEPLOY_REMOTE_REPO}" HEAD:master
  only:
    - tags