stages:
  - master
  - github

test:
  stage: master
  cache:
    paths:
      - vendor/
  before_script:
    # Install composer dependencies
    - composer install
  script:
    - ./vendor/bin/codecept run unit
  tags:
    - php

github_deploy:
    stage: github
    before_script:
        - echo "$DEPLOY_KEY_GITHUB" > ./deploy_key
        - chmod 0600 ./deploy_key
        - git remote add github git@github.com:mallgroup/mpapi-client-php.git
        - git config core.sshCommand 'ssh -o StrictHostKeyChecking=no'
    script:
        - ssh-agent bash -c 'ssh-add ./deploy_key; git pull -ff github +refs/heads/master:refs/remotes/origin/master; git push github refs/heads/master:refs/heads/master -v'
    after_script:
        - git remote remove github
        - rm -f ./deploy_key
    only:
        - master