stages:
  - master
  - github

test:
  stage: master
  cache:
    paths:
      - vendor/
  before_script:
    # Install composer dependencies
    - composer install
  script:
    - ./vendor/bin/codecept run unit
  after_script:
    - rm -rf ./vendor
  tags:
    - php

github_deploy:
    stage: github
    before_script:
        - echo "$DEPLOY_KEY_GITHUB" > ./deploy_key
        - chmod 0600 ./deploy_key
        - ssh-keyscan -v -H $CI_SERVER_NAME >> ~/.ssh/known_hosts
    script:
        - git config core.sshCommand 'ssh -vvv -T -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
        - ssh-agent bash -c 'ssh-add ./deploy_key; git remote add github git@github.com:mallgroup/mpapi-client-php.git; git push github HEAD:master'
    after_script:
        - git remote remove github
        - rm -f ./deploy_key
    only:
        - tags