stages:
  - master
  - github
  - packagist

test:
  stage: master
  cache:
    paths:
      - vendor/
  before_script:
    # Install composer dependencies
    - composer install
  script:
    - ./vendor/bin/codecept run unit
  tags:
    - php

github_deploy:
    stage: github
    before_script:
        - echo "$DEPLOY_KEY_GITHUB" > ./deploy_key
        - chmod 0600 ./deploy_key
    script:
        - git config core.sshCommand 'ssh -v -T -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
        - ssh-agent bash -c 'ssh-add ./deploy_key; git remote add github git@github.com:mallgroup/mpapi-client-php.git; git remote -v; git push -f github master'
    after_script:
        - git remote remove github
        - rm -f ./deploy_key
    only:
        - master